### ISSUE TITLE
Instructions for anyone trying to do a simple txt2img request

### ISSUE THREAD

**Issue by drgrib** [SpenserCai/sd-webui-go#65]
I'm confused why you use `DeoldifyImage` as the first and only example for this repo.

I spent a couple hours trying to get this working for a simple and (imo) much more common txt2img request due to the choice of  `DeoldifyImage` as the base example as well as relying on the `intersvc` package instead of basic idiomatic Go. For anyone looking for a simple txt2img example, here's one. For the repo owner, I recommend putting this in the README.

``` go
package main

import (
	"encoding/base64"
	"fmt"

	SdClient "github.com/SpenserCai/sd-webui-go"
	SdApiOperation "github.com/SpenserCai/sd-webui-go/stablediffusion/client/operations"
	SdApiModel "github.com/SpenserCai/sd-webui-go/stablediffusion/models"
)

func MustBeNil(err error) {
	if err != nil {
		panic(err)
	}
}

var URL = "127.0.0.1:7860"

func main() {
	sdClient := SdClient.NewStableDiffInterface(URL)

	rd := SdApiOperation.NewText2imgapiSdapiV1Txt2imgPostParams()
	rd.Body = &SdApiModel.StableDiffusionProcessingTxt2Img{
		Prompt:         "dog",
		NegativePrompt: "ugly",
		ScriptArgs:     []interface{}{},
	}

	resp, err := sdClient.Client.Operations.Text2imgapiSdapiV1Txt2imgPost(rd)
	MustBeNil(err)

	for i, s := range resp.Payload.Images {
		b, err := base64.StdEncoding.DecodeString(s)
		MustBeNil(err)
		err = os.WriteFile(fmt.Sprintf("%d.png", i), b, 0644)
		MustBeNil(err)
	}
}
```

**Comment by rootgrandfather** [comment]
great, this helps me a lot!😄

**Comment by SpenserCai** [comment]
> I'm confused why you use `DeoldifyImage` as the first and only example for this repo.
> 
> I spent a couple hours trying to get this working for a simple and (imo) much more common txt2img request due to the choice of `DeoldifyImage` as the base example as well as relying on the `intersvc` package instead of basic idiomatic Go. For anyone looking for a simple txt2img example, here's one. For the repo owner, I recommend putting this in the README.
> 
> ```go
> package main
> 
> import (
> 	"encoding/base64"
> 	"fmt"
> 
> 	SdClient "github.com/SpenserCai/sd-webui-go"
> 	SdApiOperation "github.com/SpenserCai/sd-webui-go/stablediffusion/client/operations"
> 	SdApiModel "github.com/SpenserCai/sd-webui-go/stablediffusion/models"
> )
> 
> func MustBeNil(err error) {
> 	if err != nil {
> 		panic(err)
> 	}
> }
> 
> var URL = "127.0.0.1:7860"
> 
> func main() {
> 	sdClient := SdClient.NewStableDiffInterface(URL)
> 
> 	rd := SdApiOperation.NewText2imgapiSdapiV1Txt2imgPostParams()
> 	rd.Body = &SdApiModel.StableDiffusionProcessingTxt2Img{
> 		Prompt:         "dog",
> 		NegativePrompt: "ugly",
> 		ScriptArgs:     []interface{}{},
> 	}
> 
> 	resp, err := sdClient.Client.Operations.Text2imgapiSdapiV1Txt2imgPost(rd)
> 	MustBeNil(err)
> 
> 	for i, s := range resp.Payload.Images {
> 		b, err := base64.StdEncoding.DecodeString(s)
> 		MustBeNil(err)
> 		err = os.WriteFile(fmt.Sprintf("%d.png", i), b, 0644)
> 		MustBeNil(err)
> 	}
> }
> ```

Thank you for your issue.

The reason why I use Deoldify as an example is because it is the interface of my self-developed plugin and the first interface implemented in this project.

For more implementation cases of interfaces, you can refer to [sd-webui-discord](https://github/com/SpenserCai/sd-webui-discord), which contains a large number of interface usage cases.

If you are willing, you can submit a PR to add the code you provided to the README file, and I will merge it very quickly.

Thanks again.

**Comment by drgrib** [comment]
Sure thing. Proposed in #66.

**Comment by SpenserCai** [comment]
merged,thanks so much
